<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Project;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $projects = [
            [
                'title' => 'E-Commerce Platform',
                'excerpt' => 'A full-featured e-commerce platform built with Laravel and Vue.js',
                'content' => 'This project is a comprehensive e-commerce solution that includes user management, product catalog, shopping cart, payment processing, and order management. Built with modern technologies and best practices.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'TechCorp Inc.',
                'start_date' => '2024-01-01',
                'end_date' => '2024-06-30',
                'status' => 'completed',
                'technologies' => 'Laravel, Vue.js, MySQL, Redis, Stripe',
                'project_url' => 'https://example-ecommerce.com',
                'priority' => 'high',
                'is_featured' => true,
                'is_active' => true,
                'meta_title' => 'E-Commerce Platform - Modern Online Store Solution',
                'meta_description' => 'Full-featured e-commerce platform with advanced features and modern technology stack.'
            ],
            [
                'title' => 'Mobile Banking App',
                'excerpt' => 'Cross-platform mobile banking application for iOS and Android',
                'content' => 'A secure and user-friendly mobile banking application that allows users to manage their accounts, transfer money, pay bills, and view transaction history. Built with React Native for cross-platform compatibility.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'BankSecure',
                'start_date' => '2024-03-01',
                'end_date' => '2024-12-31',
                'status' => 'in-progress',
                'technologies' => 'React Native, Node.js, MongoDB, Firebase',
                'project_url' => null,
                'priority' => 'high',
                'is_featured' => true,
                'is_active' => true,
                'meta_title' => 'Mobile Banking App - Secure Financial Management',
                'meta_description' => 'Cross-platform mobile banking application with advanced security features.'
            ],
            [
                'title' => 'Project Management Dashboard',
                'excerpt' => 'Web-based project management tool with real-time collaboration',
                'content' => 'A comprehensive project management solution that helps teams organize tasks, track progress, and collaborate effectively. Features include task management, time tracking, team collaboration, and reporting.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'StartupXYZ',
                'start_date' => '2024-02-01',
                'end_date' => '2024-08-31',
                'status' => 'planning',
                'technologies' => 'Next.js, TypeScript, PostgreSQL, Socket.io',
                'project_url' => null,
                'priority' => 'medium',
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Project Management Dashboard - Team Collaboration Tool',
                'meta_description' => 'Web-based project management solution with real-time collaboration features.'
            ],
            [
                'title' => 'AI-Powered Chatbot',
                'excerpt' => 'Intelligent chatbot with natural language processing capabilities',
                'content' => 'An advanced AI chatbot that can understand and respond to user queries in natural language. Features include sentiment analysis, multi-language support, and integration with various platforms.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'TechInnovate',
                'start_date' => '2024-04-01',
                'end_date' => '2024-09-30',
                'status' => 'completed',
                'technologies' => 'Python, TensorFlow, Flask, NLP, OpenAI',
                'project_url' => 'https://ai-chatbot-demo.com',
                'priority' => 'high',
                'is_featured' => true,
                'is_active' => true,
                'meta_title' => 'AI-Powered Chatbot - Natural Language Processing',
                'meta_description' => 'Intelligent chatbot solution with advanced AI and NLP capabilities.'
            ],
            [
                'title' => 'Social Media Platform',
                'excerpt' => 'Modern social media platform with real-time messaging and content sharing',
                'content' => 'A feature-rich social media platform that includes user profiles, content sharing, real-time messaging, and community features. Built with modern web technologies for optimal performance.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'SocialConnect',
                'start_date' => '2024-01-15',
                'end_date' => '2024-07-15',
                'status' => 'completed',
                'technologies' => 'Vue.js, Express, Socket.io, Redis, MongoDB',
                'project_url' => 'https://social-platform-demo.com',
                'priority' => 'medium',
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Social Media Platform - Modern Social Networking',
                'meta_description' => 'Feature-rich social media platform with real-time messaging and content sharing.'
            ],
            [
                'title' => 'IoT Dashboard',
                'excerpt' => 'IoT device management dashboard with real-time monitoring and control',
                'content' => 'A comprehensive IoT dashboard that allows users to monitor and control connected devices in real-time. Features include device management, data visualization, alerts, and automation.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'IoT Solutions',
                'start_date' => '2024-05-01',
                'end_date' => '2024-11-30',
                'status' => 'in-progress',
                'technologies' => 'React, Node.js, MQTT, InfluxDB, Grafana',
                'project_url' => null,
                'priority' => 'high',
                'is_featured' => true,
                'is_active' => true,
                'meta_title' => 'IoT Dashboard - Device Management & Monitoring',
                'meta_description' => 'Real-time IoT device management dashboard with advanced monitoring capabilities.'
            ],
            [
                'title' => 'Healthcare Patient Portal',
                'excerpt' => 'Secure patient portal for appointments, records, and telemedicine',
                'content' => 'A HIPAA-compliant patient portal enabling appointment booking, medical records access, and video consultations. Integrated with existing hospital systems for seamless workflows.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'MedCare Plus',
                'start_date' => '2024-02-15',
                'end_date' => '2024-09-15',
                'status' => 'completed',
                'technologies' => 'Laravel, Vue.js, Twilio, AWS, PostgreSQL',
                'project_url' => 'https://patient-portal-demo.com',
                'priority' => 'high',
                'is_featured' => true,
                'is_active' => true,
                'meta_title' => 'Healthcare Patient Portal - Telemedicine Solution',
                'meta_description' => 'Secure patient portal with appointments, records, and telemedicine features.'
            ],
            [
                'title' => 'Food Delivery App',
                'excerpt' => 'Multi-vendor food ordering and delivery platform',
                'content' => 'A full-stack food delivery application connecting restaurants with customers. Features include real-time tracking, multiple payment options, and vendor dashboards.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'QuickBite',
                'start_date' => '2024-04-01',
                'end_date' => '2024-10-31',
                'status' => 'in-progress',
                'technologies' => 'React Native, Node.js, MongoDB, Stripe, Google Maps API',
                'project_url' => null,
                'priority' => 'medium',
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Food Delivery App - Multi-vendor Ordering Platform',
                'meta_description' => 'Food ordering and delivery app with real-time tracking and vendor management.'
            ],
            [
                'title' => 'Real Estate Listing Platform',
                'excerpt' => 'Property listing and search platform with virtual tours',
                'content' => 'A modern real estate platform with advanced search, filters, virtual 3D tours, and agent management. Includes CRM and lead generation tools for agencies.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'Prime Properties',
                'start_date' => '2024-01-10',
                'end_date' => '2024-07-10',
                'status' => 'completed',
                'technologies' => 'Next.js, Prisma, PostgreSQL, Mapbox, Stripe',
                'project_url' => 'https://realestate-demo.com',
                'priority' => 'medium',
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Real Estate Platform - Property Listings & Virtual Tours',
                'meta_description' => 'Property search and listing platform with virtual tours and agent tools.'
            ],
            [
                'title' => 'Learning Management System',
                'excerpt' => 'LMS for courses, quizzes, certificates, and progress tracking',
                'content' => 'A comprehensive LMS supporting video courses, quizzes, assignments, certificates, and instructor dashboards. Built for schools and corporate training.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'EduTech Academy',
                'start_date' => '2024-03-15',
                'end_date' => '2024-12-15',
                'status' => 'in-progress',
                'technologies' => 'Laravel, React, MySQL, AWS S3, Vimeo API',
                'project_url' => null,
                'priority' => 'high',
                'is_featured' => true,
                'is_active' => true,
                'meta_title' => 'LMS - Learning Management System',
                'meta_description' => 'Full-featured LMS with courses, quizzes, and progress tracking.'
            ],
            [
                'title' => 'Inventory Management System',
                'excerpt' => 'Warehouse and inventory tracking with barcode and reporting',
                'content' => 'An inventory and warehouse management system with barcode scanning, stock alerts, purchase orders, and comprehensive reporting for retail and distribution.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'SupplyChain Pro',
                'start_date' => '2024-05-10',
                'end_date' => '2024-11-10',
                'status' => 'review',
                'technologies' => 'Laravel, Vue.js, MySQL, Redis, PDF export',
                'project_url' => null,
                'priority' => 'medium',
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Inventory Management - Warehouse & Stock Tracking',
                'meta_description' => 'Inventory and warehouse management with barcode and reporting.'
            ],
            [
                'title' => 'Fitness & Wellness App',
                'excerpt' => 'Workout plans, nutrition tracking, and progress analytics',
                'content' => 'A fitness app with personalized workout plans, nutrition logging, progress charts, and integration with wearables. Supports trainers and gyms.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'FitLife',
                'start_date' => '2024-02-01',
                'end_date' => '2024-08-31',
                'status' => 'completed',
                'technologies' => 'React Native, Node.js, MongoDB, Chart.js, Stripe',
                'project_url' => 'https://fitlife-app.com',
                'priority' => 'medium',
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Fitness App - Workouts & Nutrition Tracking',
                'meta_description' => 'Fitness and wellness app with workouts, nutrition, and progress tracking.'
            ],
            [
                'title' => 'CRM for Sales Teams',
                'excerpt' => 'Customer relationship management with pipeline and automation',
                'content' => 'A CRM designed for sales teams with lead management, pipeline stages, email integration, and automation workflows. Includes reporting and forecasting.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'SalesForce Pro',
                'start_date' => '2024-04-15',
                'end_date' => '2024-10-15',
                'status' => 'in-progress',
                'technologies' => 'Vue.js, Laravel, PostgreSQL, Redis, SendGrid',
                'project_url' => null,
                'priority' => 'high',
                'is_featured' => true,
                'is_active' => true,
                'meta_title' => 'CRM - Sales Pipeline & Lead Management',
                'meta_description' => 'CRM for sales teams with pipeline, automation, and reporting.'
            ],
            [
                'title' => 'Restaurant POS System',
                'excerpt' => 'Point of sale and table management for restaurants',
                'content' => 'A complete POS solution for restaurants with table management, order taking, kitchen display, and billing. Supports multiple branches and reporting.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'DineEasy',
                'start_date' => '2024-01-20',
                'end_date' => '2024-06-20',
                'status' => 'completed',
                'technologies' => 'React, Node.js, SQLite, Thermal printer API',
                'project_url' => 'https://pos-demo.com',
                'priority' => 'medium',
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Restaurant POS - Table & Order Management',
                'meta_description' => 'POS and table management system for restaurants.'
            ],
            [
                'title' => 'Travel Booking Portal',
                'excerpt' => 'Flights, hotels, and packages with payment and vouchers',
                'content' => 'A travel booking platform for flights, hotels, and packages. Includes search, filters, payment gateway, and e-voucher generation for customers.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'Wanderlust Travel',
                'start_date' => '2024-03-01',
                'end_date' => '2024-11-30',
                'status' => 'on-hold',
                'technologies' => 'Next.js, Laravel, MySQL, Stripe, Amadeus API',
                'project_url' => null,
                'priority' => 'low',
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Travel Booking - Flights, Hotels & Packages',
                'meta_description' => 'Travel booking portal with flights, hotels, and package deals.'
            ],
            [
                'title' => 'Event Ticketing Platform',
                'excerpt' => 'Event creation, ticket sales, and check-in management',
                'content' => 'An event ticketing platform where organizers can create events, sell tickets, and manage check-ins. Includes QR codes and email tickets.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'EventHub',
                'start_date' => '2024-05-01',
                'end_date' => '2024-12-01',
                'status' => 'planning',
                'technologies' => 'Laravel, Vue.js, MySQL, Stripe, QR code',
                'project_url' => null,
                'priority' => 'medium',
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Event Ticketing - Sell & Manage Event Tickets',
                'meta_description' => 'Event ticketing platform with sales and check-in management.'
            ],
            [
                'title' => 'HR & Payroll System',
                'excerpt' => 'Employee management, attendance, leave, and payroll processing',
                'content' => 'An HR and payroll system with employee records, attendance, leave management, and automated payroll calculation. Includes tax and compliance features.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'HR Solutions Ltd',
                'start_date' => '2024-02-10',
                'end_date' => '2024-08-10',
                'status' => 'completed',
                'technologies' => 'Laravel, React, MySQL, PDF, Excel export',
                'project_url' => 'https://hr-payroll-demo.com',
                'priority' => 'high',
                'is_featured' => true,
                'is_active' => true,
                'meta_title' => 'HR & Payroll - Employee & Payroll Management',
                'meta_description' => 'HR and payroll system with attendance, leave, and payroll.'
            ],
            [
                'title' => 'Blog & CMS Platform',
                'excerpt' => 'Multi-author blog with SEO and analytics',
                'content' => 'A content management system for blogs with multi-author support, categories, tags, SEO meta, and built-in analytics. Optimized for performance.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'Content Studio',
                'start_date' => '2024-01-05',
                'end_date' => '2024-05-05',
                'status' => 'completed',
                'technologies' => 'Next.js, Strapi, PostgreSQL, Redis, Vercel',
                'project_url' => 'https://blog-cms-demo.com',
                'priority' => 'medium',
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Blog CMS - Multi-author & SEO',
                'meta_description' => 'Blog and CMS platform with SEO and analytics.'
            ],
            [
                'title' => 'Fleet Management System',
                'excerpt' => 'Vehicle tracking, maintenance, and driver assignment',
                'content' => 'A fleet management system for tracking vehicles, scheduling maintenance, assigning drivers, and monitoring fuel and routes. Includes reporting and alerts.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'LogiTrack',
                'start_date' => '2024-04-01',
                'end_date' => '2024-10-31',
                'status' => 'in-progress',
                'technologies' => 'Vue.js, Laravel, MySQL, GPS API, Google Maps',
                'project_url' => null,
                'priority' => 'high',
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Fleet Management - Vehicle & Driver Tracking',
                'meta_description' => 'Fleet management with tracking, maintenance, and reporting.'
            ],
            [
                'title' => 'Donation & Fundraising Platform',
                'excerpt' => 'Campaign creation, donations, and donor management',
                'content' => 'A platform for nonprofits to create campaigns, accept donations, and manage donors. Includes recurring donations, receipts, and campaign analytics.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'GiveBack NGO',
                'start_date' => '2024-03-20',
                'end_date' => '2024-09-20',
                'status' => 'completed',
                'technologies' => 'Laravel, React, MySQL, Stripe, Mailchimp',
                'project_url' => 'https://donate-demo.com',
                'priority' => 'medium',
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Donation Platform - Fundraising & Donor Management',
                'meta_description' => 'Donation and fundraising platform for nonprofits.'
            ],
            [
                'title' => 'Property Rental Marketplace',
                'excerpt' => 'Short-term and long-term rental listings with bookings',
                'content' => 'A rental marketplace for properties with search, filters, booking calendar, and secure payments. Supports hosts and guests with reviews and messaging.',
                'featured_image' => 'images/projects/1756371321_xVFuYsgWfh.webp',
                'client' => 'StayHere',
                'start_date' => '2024-06-01',
                'end_date' => '2024-12-31',
                'status' => 'planning',
                'technologies' => 'Next.js, Prisma, PostgreSQL, Stripe, SendGrid',
                'project_url' => null,
                'priority' => 'low',
                'is_featured' => false,
                'is_active' => true,
                'meta_title' => 'Rental Marketplace - Property Bookings',
                'meta_description' => 'Property rental marketplace with bookings and payments.'
            ]
        ];

        foreach ($projects as $project) {
            $project['slug'] = \Illuminate\Support\Str::slug($project['title']);
            Project::create($project);
        }
    }
}
